import { GeminiClientError } from "../providers/gemini-client";
import { requestStructuredText } from "../providers/structured-text";
export type AnalyticsInput = { platform: "youtube" | "tiktok" | "instagram" | "facebook" | "shopee"; contentTitle: string; views?: number; likes?: number; comments?: number; shares?: number; saves?: number; watchTime?: number; retentionRate?: number; clicks?: number; conversions?: number; revenue?: number; contentObjective: string; niche?: string };
export type PerformanceRecommendation = { performance_summary: string; scorecard: { reach_score: number; engagement_score: number; retention_score: number; conversion_score: number; overall_score: number }; diagnosis: { strengths: string[]; weaknesses: string[]; likely_reason: string[] }; recommendations: { hook_improvement: string[]; caption_improvement: string[]; cta_improvement: string[]; editing_improvement: string[]; next_content_ideas: string[] }; decision: { action: "repeat" | "revise" | "stop" | "scale"; reason: string }; knowledge_base_updates: { tags: string[]; learned_pattern: string; should_save: boolean }; next_actions: string[] };
export type PerformanceRecommendationMeta = { provider: "gemini" | "dummy"; mode: "real" | "fallback"; error_reason?: string; generated_at: string };
type AnalyticsEngineOptions = { apiKey?: string; mode?: "REAL" | "DUMMY"; timeoutMs?: number; fetchImpl?: (input: string, init?: RequestInit) => Promise<Response> };

export async function generatePerformanceRecommendation(input: AnalyticsInput, options: AnalyticsEngineOptions = {}) {
  validateAnalyticsInput(input); const fallback = buildRuleBasedRecommendation(input);
  if (options.mode !== "REAL" || !options.apiKey) return { data: fallback, meta: fallbackMeta(options.mode === "REAL" ? "API_KEY_MISSING" : "DUMMY_MODE_REQUESTED") };
  try {
    return { data: normalizeRecommendation(await requestStructuredText<Partial<PerformanceRecommendation>>(analyticsPrompt(input, fallback), options), input), meta: { provider: "gemini" as const, mode: "real" as const, generated_at: new Date().toISOString() } };
  } catch (error) { return { data: fallback, meta: fallbackMeta(error instanceof GeminiClientError ? error.code : "INVALID_RESPONSE") }; }
}
export function validateAnalyticsInput(input: Partial<AnalyticsInput>) { for (const field of ["platform", "contentTitle", "contentObjective"] as const) if (!input[field]?.trim()) throw new AnalyticsValidationError(`${field} is required.`); }
export class AnalyticsValidationError extends Error { code = "VALIDATION_ERROR" as const; }

export function buildRuleBasedRecommendation(input: AnalyticsInput): PerformanceRecommendation {
  const views = metric(input.views), engagementCount = metric(input.likes) + metric(input.comments) * 2 + metric(input.shares) * 3 + metric(input.saves) * 2, engagementRate = views ? engagementCount / views * 100 : 0, clickRate = views ? metric(input.clicks) / views * 100 : 0, conversionRate = metric(input.clicks) ? metric(input.conversions) / metric(input.clicks) * 100 : 0;
  const reach = bounded(Math.log10(views + 1) * 18), engagement = bounded(engagementRate * 7), retention = bounded(input.retentionRate ?? 0), conversion = bounded(clickRate * 5 + conversionRate * 7), overall = bounded(reach * .25 + engagement * .25 + retention * .3 + conversion * .2), action = performanceDecision(overall, reach);
  return { performance_summary: `${input.contentTitle} memperoleh overall score ${overall}/100 di ${input.platform}. Fokus evaluasi berikutnya adalah hook, retention, dan CTA.`, scorecard: { reach_score: reach, engagement_score: engagement, retention_score: retention, conversion_score: conversion, overall_score: overall }, diagnosis: { strengths: strengths(reach, engagement, retention, conversion), weaknesses: weaknesses(reach, engagement, retention, conversion), likely_reason: likelyReasons(reach, engagement, retention, conversion) }, recommendations: { hook_improvement: ["Uji hook yang menyampaikan manfaat dalam tiga detik pertama.", "Gunakan satu masalah audience yang spesifik."], caption_improvement: ["Gunakan caption ringkas dengan keyword utama.", "Tambahkan konteks agar audience memahami manfaat konten."], cta_improvement: ["Sesuaikan CTA dengan platform dan objective.", "Gunakan satu primary CTA agar tidak membingungkan."], editing_improvement: ["Kurangi dead air.", "Tambahkan pattern interrupt pada bagian dengan potensi drop-off."], next_content_ideas: [`Buat variasi hook untuk ${input.niche || input.contentTitle}.`, "Uji format checklist singkat.", "Buat follow-up berdasarkan komentar audience."] }, decision: { action, reason: decisionReason(action, overall) }, knowledge_base_updates: { tags: [input.platform, input.niche || "general", action, overall >= 70 ? "winning-pattern" : "optimization-needed"], learned_pattern: `${input.platform} content with ${retention >= 70 ? "strong" : "improvable"} retention and ${engagement >= 60 ? "healthy" : "low"} engagement.`, should_save: overall >= 60 }, next_actions: ["Review scorecard.", "Pilih satu eksperimen hook.", "Update CTA dan caption.", "Simpan learning yang relevan ke Knowledge Base."] };
}
function normalizeRecommendation(value: Partial<PerformanceRecommendation>, input: AnalyticsInput): PerformanceRecommendation {
  const fallback = buildRuleBasedRecommendation(input), scores = value.scorecard;
  const scorecard = { reach_score: bounded(scores?.reach_score ?? fallback.scorecard.reach_score), engagement_score: bounded(scores?.engagement_score ?? fallback.scorecard.engagement_score), retention_score: bounded(scores?.retention_score ?? fallback.scorecard.retention_score), conversion_score: bounded(scores?.conversion_score ?? fallback.scorecard.conversion_score), overall_score: bounded(scores?.overall_score ?? fallback.scorecard.overall_score) }, action = performanceDecision(scorecard.overall_score, scorecard.reach_score);
  return { performance_summary: text(value.performance_summary, fallback.performance_summary), scorecard, diagnosis: { strengths: list(value.diagnosis?.strengths, fallback.diagnosis.strengths), weaknesses: list(value.diagnosis?.weaknesses, fallback.diagnosis.weaknesses), likely_reason: list(value.diagnosis?.likely_reason, fallback.diagnosis.likely_reason) }, recommendations: { hook_improvement: list(value.recommendations?.hook_improvement, fallback.recommendations.hook_improvement), caption_improvement: list(value.recommendations?.caption_improvement, fallback.recommendations.caption_improvement), cta_improvement: list(value.recommendations?.cta_improvement, fallback.recommendations.cta_improvement), editing_improvement: list(value.recommendations?.editing_improvement, fallback.recommendations.editing_improvement), next_content_ideas: list(value.recommendations?.next_content_ideas, fallback.recommendations.next_content_ideas) }, decision: { action, reason: text(value.decision?.reason, decisionReason(action, scorecard.overall_score)) }, knowledge_base_updates: { tags: list(value.knowledge_base_updates?.tags, fallback.knowledge_base_updates.tags), learned_pattern: text(value.knowledge_base_updates?.learned_pattern, fallback.knowledge_base_updates.learned_pattern), should_save: value.knowledge_base_updates?.should_save ?? fallback.knowledge_base_updates.should_save }, next_actions: list(value.next_actions, fallback.next_actions) };
}
export function performanceDecision(overall: number, reach = overall): PerformanceRecommendation["decision"]["action"] { if (overall >= 80) return "scale"; if (overall >= 62 || reach >= 75) return "repeat"; if (overall >= 30) return "revise"; return "stop"; }
function strengths(reach: number, engagement: number, retention: number, conversion: number) { const rows = [[reach, "Reach memiliki momentum."], [engagement, "Audience aktif berinteraksi."], [retention, "Retention cukup kuat."], [conversion, "CTA menghasilkan aksi."]] as const; const result: string[] = rows.filter(([score]) => score >= 60).map(([, note]) => note); if (!result.length) result.push("Data awal sudah tersedia untuk eksperimen berikutnya."); return result; }
function weaknesses(reach: number, engagement: number, retention: number, conversion: number) { const rows = [[reach, "Reach masih terbatas."], [engagement, "Engagement perlu ditingkatkan."], [retention, "Retention perlu perbaikan hook dan editing."], [conversion, "CTA belum menghasilkan aksi yang cukup."]] as const; return rows.filter(([score]) => score < 60).map(([, note]) => note); }
function likelyReasons(reach: number, engagement: number, retention: number, conversion: number) { return [reach < 60 ? "Distribusi atau keyword belum optimal." : "Distribusi awal bekerja.", engagement < 60 ? "Topik belum cukup memicu respons audience." : "Topik relevan dengan audience.", retention < 60 ? "Hook atau pacing perlu diperbaiki." : "Opening dan pacing cukup efektif.", conversion < 60 ? "CTA perlu lebih spesifik." : "CTA sudah cukup jelas."]; }
function decisionReason(action: PerformanceRecommendation["decision"]["action"], score: number) { return action === "scale" ? `Score ${score} layak diperluas dengan variasi konten.` : action === "repeat" ? `Score ${score} layak diuji ulang dengan iterasi kecil.` : action === "revise" ? `Score ${score} memerlukan revisi hook, editing, atau CTA.` : `Score ${score} terlalu rendah; hentikan format ini dan uji angle baru.`; }
function analyticsPrompt(input: AnalyticsInput, baseline: PerformanceRecommendation) { return `Return only valid JSON recommendations using this rule-based scorecard without inventing metrics: ${JSON.stringify(baseline.scorecard)}. Required keys: performance_summary, scorecard, diagnosis, recommendations, decision, knowledge_base_updates, next_actions. Input: ${JSON.stringify(input)}`; }
function metric(value?: number) { return typeof value === "number" && Number.isFinite(value) ? Math.max(0, value) : 0; }
function bounded(value: number) { return Math.min(100, Math.max(0, Math.round(value))); }
function text(value: unknown, fallback: string) { return typeof value === "string" && value.trim() ? value.trim() : fallback; }
function list(value: unknown, fallback: string[]) { return Array.isArray(value) && value.some((item) => typeof item === "string" && item.trim()) ? value.filter((item): item is string => typeof item === "string" && Boolean(item.trim())).map((item) => item.trim()) : fallback; }
function fallbackMeta(errorReason: string): PerformanceRecommendationMeta { return { provider: "dummy", mode: "fallback", error_reason: errorReason, generated_at: new Date().toISOString() }; }
