-- AlterEnum
ALTER TYPE "ContentStatus" ADD VALUE IF NOT EXISTS 'REVIEW';
ALTER TYPE "ContentStatus" ADD VALUE IF NOT EXISTS 'APPROVED';

-- AlterTable
ALTER TABLE "ContentItem" ADD COLUMN IF NOT EXISTS "caption" TEXT NOT NULL DEFAULT '';
