ALTER TABLE "PostAnalytics"
  ADD COLUMN IF NOT EXISTS "postUrl" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "averageViewDuration" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "followersGained" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "postedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "recordedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS "notes" TEXT NOT NULL DEFAULT '';
