import { randomUUID } from "node:crypto";
import { generateAffiliatePlan } from "../affiliate/affiliate-engine";
import { generatePerformanceRecommendation } from "../analytics/analytics-engine";
import { generateClipPlan } from "../clipper/clipper-engine";
import { generateContentPackage } from "../content-creator/content-creator-engine";
import { generateIntelligenceBrief } from "../intelligence/intelligence-engine";
import type { IntelligenceBrief } from "../intelligence/intelligence-engine";
import { generatePublishingPackage } from "../publishing/publishing-engine";
import { createCeoExecutionPlan } from "./ceo-agent";
import type { AgentExecutionLog, AgentName, OrchestrationInput, OrchestrationOutput } from "./orchestration-types";
import { saveWorkflow } from "./orchestration-repository";
import { runPolicyAgent } from "./policy-agent";

type OrchestratorOptions = { apiKey?: string; mode?: "REAL" | "DUMMY"; timeoutMs?: number; fetchImpl?: (input: string, init?: RequestInit) => Promise<Response>; failAgents?: AgentName[] };
export async function orchestrateAgents(input: OrchestrationInput, options: OrchestratorOptions = {}): Promise<OrchestrationOutput> {
  validate(input); const workflowId = `workflow_${randomUUID()}`, plan = createCeoExecutionPlan(input), outputs: Record<string, unknown> = {}, logs: AgentExecutionLog[] = [], language = input.language || "Bahasa Indonesia";
  await execute("CEO Agent", logs, options, async () => { outputs.ceo = plan; return `${plan.selected_agents.length} agent dipilih.`; });
  await execute("Research Agent", logs, options, async () => { const result = await generateIntelligenceBrief({ niche: input.niche, platform: input.platform, contentObjective: input.objective, targetAudience: input.targetAudience, language, contentType: input.contentType }, options); outputs.research = result; return `Intelligence Brief ${result.meta.mode}.`; });
  await execute("Creator Agent", logs, options, async () => { const brief = nestedData<IntelligenceBrief>(outputs.research); const result = await generateContentPackage({ intelligenceBrief: brief, niche: input.niche, platform: input.platform, contentObjective: input.objective, targetAudience: input.targetAudience, language, contentType: input.contentType, tone: "Professional and approachable", duration: "30 seconds" }, options); outputs.creator = result; return `Content package ${result.meta.mode}.`; });
  if (plan.selected_agents.includes("Clipper Agent")) await execute("Clipper Agent", logs, options, async () => { const result = await generateClipPlan({ sourceType: input.transcript ? "upload" : "youtube_url", sourceTitle: input.sourceTitle || input.objective, transcript: input.transcript, platform: normalizePlatform(input.platform), language, contentObjective: input.objective, niche: input.niche }, options); outputs.clipper = result; return `${result.data.best_segments.length} clip segment tersedia.`; });
  if (plan.selected_agents.includes("Affiliate Agent")) await execute("Affiliate Agent", logs, options, async () => { const result = await generateAffiliatePlan({ productName: input.productName, productCategory: input.productCategory || input.niche, platform: normalizeAffiliatePlatform(input.platform), targetAudience: input.targetAudience, contentObjective: input.objective, language }, options); outputs.affiliate = result; return `Affiliate score ${result.data.product_score.overall_score}.`; });
  await execute("Policy Agent", logs, options, async () => { outputs.policy = runPolicyAgent(outputs); return `Policy risk ${(outputs.policy as { risk_level: string }).risk_level}.`; });
  await execute("Publishing Agent", logs, options, async () => { const creator = nestedData<{ platform_metadata?: { title?: string } }>(outputs.creator), policy = outputs.policy as { risk_level?: string } | undefined; const result = await generatePublishingPackage({ contentPackage: creator, clipPlan: nestedData(outputs.clipper), affiliatePlan: nestedData(outputs.affiliate), platform: normalizeAffiliatePlatform(input.platform), contentTitle: creator?.platform_metadata?.title || input.objective, contentObjective: input.objective, language, approvalRequired: policy?.risk_level !== "low" || true }, options); outputs.publishing = result; return `Publishing package ${result.meta.mode}.`; });
  if (plan.selected_agents.includes("Analytics Agent")) await execute("Analytics Agent", logs, options, async () => { const result = await generatePerformanceRecommendation({ platform: normalizeAffiliatePlatform(input.platform), contentTitle: input.objective, contentObjective: input.objective, niche: input.niche, ...input.metrics }, options); outputs.analytics = result; return `Analytics recommendation: ${result.data.decision.action}.`; });
  const fallback = logs.some((log) => log.status === "fallback" || log.status === "failed");
  return saveWorkflow({ workflow_id: workflowId, execution_plan: plan.execution_plan, selected_agents: plan.selected_agents, priority_order: plan.priority_order, outputs, recommendations: ["Gunakan output Research sebagai sumber Creator.", "Lakukan Policy Review sebelum export.", ...(outputs.analytics ? ["Masukkan performance learning ke Knowledge Base."] : [])], risks: [...plan.risks, ...(fallback ? ["Satu atau lebih agent menggunakan fallback; review output sebelum export."] : [])], next_actions: ["Review output agent.", "Setujui publishing package.", "Export bundle manual.", "Tambahkan metrics setelah posting."], execution_logs: logs, status: fallback ? "completed_with_fallback" : "completed" });
}
async function execute(agent: AgentName, logs: AgentExecutionLog[], options: OrchestratorOptions, task: () => Promise<string>) { const started = Date.now(), start = new Date(started).toISOString(); try { if (options.failAgents?.includes(agent)) throw new Error("SIMULATED_AGENT_FAILURE"); const summary = await task(); const fallback = /fallback/i.test(summary); logs.push(log(agent, start, started, fallback ? "fallback" : "completed", summary)); } catch (error) { logs.push(log(agent, start, started, "failed", `${error instanceof Error ? error.message : "Agent failed."} Workflow dilanjutkan dengan output yang tersedia.`)); } }
function log(agent_name: AgentName, start_time: string, started: number, status: AgentExecutionLog["status"], result_summary: string): AgentExecutionLog { const end = Date.now(); return { agent_name, start_time, end_time: new Date(end).toISOString(), duration: end - started, status, result_summary }; }
function validate(input: Partial<OrchestrationInput>) { for (const field of ["objective", "platform", "niche", "targetAudience", "contentType"] as const) if (!input[field]?.trim()) throw new OrchestrationValidationError(`${field} is required.`); }
export class OrchestrationValidationError extends Error { code = "VALIDATION_ERROR" as const; }
function normalizePlatform(value: string): "youtube" | "tiktok" | "instagram" | "facebook" { const platform = value.toLowerCase(); return platform.includes("youtube") ? "youtube" : platform.includes("instagram") ? "instagram" : platform.includes("facebook") ? "facebook" : "tiktok"; }
function normalizeAffiliatePlatform(value: string): "youtube" | "tiktok" | "instagram" | "facebook" | "shopee" { return value.toLowerCase().includes("shopee") ? "shopee" : normalizePlatform(value); }
function nestedData<T = Record<string, unknown>>(value: unknown): T | undefined { return (value as { data?: T } | undefined)?.data; }
