ALTER TYPE "ProcessingStatus" ADD VALUE IF NOT EXISTS 'GENERATING_SUBTITLE';
ALTER TYPE "ProcessingStatus" ADD VALUE IF NOT EXISTS 'GENERATING_THUMBNAIL';

ALTER TABLE "GeneratedClip"
ADD COLUMN IF NOT EXISTS "thumbnailUrl" TEXT;

ALTER TABLE "MediaProcessingJob"
ADD COLUMN IF NOT EXISTS "logs" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
