import { notFound } from "next/navigation";
import { AnalysisDetailActions } from "@/components/analysis-detail-actions";
import { getDataDrivenAnalysis } from "@/lib/intelligence/analysis-engine/repository";

export const runtime = "nodejs";

export default async function AnalysisDetailPage({ params }: { params: { id: string } }) {
  const analysis = await getDataDrivenAnalysis(params.id);
  if (!analysis) notFound();
  const breakdown = analysis.scoreBreakdown ?? {};
  const sources = analysis.sourceBreakdown ?? [];
  return <div className="space-y-6"><header><div className="text-xs font-semibold uppercase text-primary">Persisted intelligence result</div><div className="mt-3 flex flex-wrap items-center gap-2"><Badge tone={analysis.isDemo ? "warning" : "success"}>{analysis.isDemo ? "Demo Analysis" : "Real-source Analysis"}</Badge><Badge tone="default">{analysis.mode}</Badge><Badge tone="info">{analysis.confidence}% confidence</Badge></div><h1 className="mt-4 text-3xl font-semibold text-white md:text-5xl">{analysis.topic}</h1><p className="mt-3 max-w-4xl text-slate-300">{analysis.summary}</p><p className="mt-2 text-xs text-slate-500">Created {new Date(analysis.createdAt).toLocaleString("id-ID")}</p></header><section className="grid gap-4 md:grid-cols-3"><Metric label="Trend Stage" value={analysis.trendStage} /><Metric label="Opportunity" value={analysis.opportunityLevel} /><Metric label="Risk" value={analysis.riskLevel} /></section><section className="grid gap-6 xl:grid-cols-[1.2fr_0.8fr]"><div className="space-y-6"><Panel title="Executive Summary"><p>{analysis.summary}</p></Panel><Panel title="Audience & Content Gap"><p><strong>Audience:</strong> {analysis.audience}</p><p className="mt-3"><strong>Gap:</strong> {analysis.contentGap}</p></Panel><ListPanel title="Recommended Angles" values={analysis.recommendedAngles} /><ListPanel title="Recommended Hooks" values={analysis.recommendedHooks} /><ListPanel title="Recommended Formats" values={analysis.recommendedContentFormats} /><ListPanel title="Action Plan" values={analysis.actionPlan} /></div><div className="space-y-6"><Panel title="Platform Recommendation"><p>{analysis.platformRecommendation}</p></Panel><Panel title="Score Breakdown"><div className="space-y-3">{Object.entries(breakdown).map(([label, value]) => <div key={label}><div className="flex justify-between text-sm text-slate-300"><span>{label}</span><span>{value}</span></div><div className="mt-1 h-1.5 rounded-full bg-white/[0.08]"><div className="h-full rounded-full bg-primary" style={{ width: `${value}%` }} /></div></div>)}</div></Panel><Panel title="Source Breakdown"><div className="space-y-3">{sources.map((source) => <div key={`${source.source}-${source.collectedAt}`} className="rounded-lg border border-white/[0.06] p-3 text-xs text-slate-300"><div className="font-semibold text-white">{source.source}</div><div className="mt-1">{source.isDemo ? "Demo Source" : "Real Public Data"} · {source.confidence}% confidence</div><div className="mt-1">{new Date(source.collectedAt).toLocaleString("id-ID")}</div></div>)}</div></Panel><Panel title="Notes"><p>{analysis.notes}</p></Panel><AnalysisDetailActions analysis={analysis} /></div></section></div>;
}

function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-xl border border-white/[0.06] bg-[#111A2E] p-5"><h2 className="text-lg font-semibold text-white">{title}</h2><div className="mt-3 text-sm leading-6 text-slate-300">{children}</div></section>; }
function ListPanel({ title, values = [] }: { title: string; values?: string[] }) { return <Panel title={title}>{values.length ? <ul className="space-y-2">{values.map((value) => <li key={value}>• {value}</li>)}</ul> : <p>No recommendation recorded.</p>}</Panel>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-white/[0.06] bg-[#111A2E] p-4"><div className="text-xs font-semibold uppercase text-slate-500">{label}</div><div className="mt-2 text-xl font-semibold text-white">{value}</div></div>; }
function Badge({ children, tone }: { children: React.ReactNode; tone: "default" | "info" | "success" | "warning" }) { const colors = tone === "success" ? "border-emerald-400/25 bg-emerald-400/10 text-emerald-200" : tone === "warning" ? "border-amber-400/25 bg-amber-400/10 text-amber-100" : tone === "info" ? "border-blue-400/25 bg-blue-400/10 text-blue-100" : "border-white/[0.08] bg-white/[0.03] text-slate-300"; return <span className={`rounded-full border px-2.5 py-1 text-xs font-semibold ${colors}`}>{children}</span>; }

