"use client";
import { Bot, LoaderCircle, Play, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { DashboardPanel } from "@/components/dashboard/ui";
import type { OrchestrationOutput } from "@/lib/agents/orchestration-types";
const initial = { objective: "Buat short-form content edukatif untuk meningkatkan engagement creator UMKM", platform: "tiktok", niche: "Creator Economy", targetAudience: "UMKM dan solo creator", contentType: "Short-form explainer" };
export function AgentOrchestrationPanel() {
  const [form, setForm] = useState(initial), [workflow, setWorkflow] = useState<OrchestrationOutput | null>(null), [error, setError] = useState(""), [loading, setLoading] = useState(false);
  async function run() { setLoading(true); setError(""); try { const response = await fetch("/api/agents/orchestrate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }), payload = await response.json(); if (!response.ok || !payload.success) throw new Error(payload.error?.message || "Workflow gagal dijalankan."); setWorkflow(payload); } catch (requestError) { setWorkflow(null); setError(requestError instanceof Error ? requestError.message : "Workflow gagal dijalankan."); } finally { setLoading(false); } }
  return <DashboardPanel title="Multi-Agent Orchestration v1" description="CEO Agent memilih tim, menjalankan workflow, dan mengumpulkan output dengan fallback aman."><div className="grid gap-5 xl:grid-cols-[0.82fr_1.18fr]"><div className="grid gap-3"><Field label="Objective" value={form.objective} onChange={(objective) => setForm({ ...form, objective })} /><Field label="Niche" value={form.niche} onChange={(niche) => setForm({ ...form, niche })} /><Field label="Target audience" value={form.targetAudience} onChange={(targetAudience) => setForm({ ...form, targetAudience })} /><Select label="Platform" value={form.platform} options={["tiktok", "youtube", "instagram", "facebook", "shopee"]} onChange={(platform) => setForm({ ...form, platform })} /><button onClick={run} disabled={loading} className="inline-flex items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-blue-500 to-violet-500 px-4 py-3 text-sm font-semibold text-white disabled:opacity-60">{loading ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Play className="h-4 w-4" />} Run CEO Workflow</button></div><div className="rounded-xl border border-white/[0.07] bg-white/[0.025] p-4">{workflow ? <Result workflow={workflow} /> : <Empty title={error || "Workflow belum dijalankan"} />}</div></div></DashboardPanel>;
}
function Result({ workflow }: { workflow: OrchestrationOutput }) { return <div><div className="flex flex-wrap gap-2"><Badge>{workflow.status}</Badge><Badge>{workflow.selected_agents.length} agents</Badge></div><h3 className="mt-4 text-sm font-semibold text-white">Execution Queue</h3><div className="mt-2 grid gap-2">{workflow.execution_logs.map((item) => <div key={`${item.agent_name}-${item.start_time}`} className="flex items-center justify-between gap-3 rounded-lg border border-white/[0.06] bg-white/[0.025] p-3"><div><div className="text-xs font-semibold text-slate-300">{item.agent_name}</div><p className="mt-1 text-[11px] leading-4 text-slate-600">{item.result_summary}</p></div><span className={`shrink-0 rounded-full border px-2 py-1 text-[9px] font-semibold uppercase ${item.status === "failed" ? "border-rose-300/20 text-rose-200" : item.status === "fallback" ? "border-amber-300/20 text-amber-200" : "border-emerald-300/20 text-emerald-200"}`}>{item.status}</span></div>)}</div></div>; }
function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label><Label>{label}</Label><input value={value} onChange={(event) => onChange(event.target.value)} className="premium-input mt-1.5 px-3 py-2.5 text-sm" /></label>; }
function Select({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (value: string) => void }) { return <label><Label>{label}</Label><select value={value} onChange={(event) => onChange(event.target.value)} className="premium-input mt-1.5 px-3 py-2.5 text-sm">{options.map((option) => <option key={option}>{option}</option>)}</select></label>; }
function Label({ children }: { children: React.ReactNode }) { return <span className="text-[10px] font-semibold uppercase tracking-[0.14em] text-slate-600">{children}</span>; }
function Badge({ children }: { children: React.ReactNode }) { return <span className="inline-flex items-center gap-1 rounded-full border border-cyan-300/15 bg-cyan-300/[0.06] px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wide text-cyan-100"><ShieldCheck className="h-3 w-3" />{children}</span>; }
function Empty({ title }: { title: string }) { return <div className="grid min-h-72 place-items-center text-center"><div><Bot className="mx-auto h-7 w-7 text-cyan-200" /><p className="mt-3 text-sm font-semibold text-slate-300">{title}</p><p className="mt-1 text-xs text-slate-600">Isi objective lalu jalankan CEO Agent.</p></div></div>; }
