"use client";
import { ChartNoAxesCombined, LoaderCircle, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { DashboardPanel } from "@/components/dashboard/ui";
import type { PerformanceRecommendation, PerformanceRecommendationMeta } from "@/lib/analytics/analytics-engine";
const initial = { platform: "tiktok", contentTitle: "3 Produk Viral untuk Workspace Minimalis", views: 684000, likes: 72000, comments: 3400, shares: 9100, saves: 12200, watchTime: 14800, retentionRate: 78, clicks: 18400, conversions: 812, revenue: 4800000, contentObjective: "Increase affiliate conversion", niche: "Workspace Product" };
export function AnalyticsEnginePanel() {
  const [form, setForm] = useState(initial), [data, setData] = useState<PerformanceRecommendation | null>(null), [meta, setMeta] = useState<PerformanceRecommendationMeta | null>(null), [error, setError] = useState(""), [loading, setLoading] = useState(false);
  async function generate() { setLoading(true); setError(""); try { const response = await fetch("/api/analytics/recommendation", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }), payload = await response.json(); if (!response.ok || !payload.success) throw new Error(payload.error?.message ?? "Recommendation gagal dibuat."); setData(payload.data); setMeta(payload.meta); } catch (requestError) { setData(null); setMeta(null); setError(requestError instanceof Error ? requestError.message : "Recommendation gagal dibuat."); } finally { setLoading(false); } }
  return <DashboardPanel title="Analytics & Recommendation Engine v1" description="Masukkan metrics manual untuk menghasilkan scorecard dan recommendation."><div className="grid gap-5 xl:grid-cols-[0.82fr_1.18fr]"><div className="grid gap-3 sm:grid-cols-2"><Field label="Content title" value={form.contentTitle} onChange={(contentTitle) => setForm({ ...form, contentTitle })} wide /><Select label="Platform" value={form.platform} options={["tiktok", "youtube", "instagram", "facebook", "shopee"]} onChange={(platform) => setForm({ ...form, platform })} /><NumberField label="Views" value={form.views} onChange={(views) => setForm({ ...form, views })} /><NumberField label="Likes" value={form.likes} onChange={(likes) => setForm({ ...form, likes })} /><NumberField label="Retention %" value={form.retentionRate} onChange={(retentionRate) => setForm({ ...form, retentionRate })} /><NumberField label="Clicks" value={form.clicks} onChange={(clicks) => setForm({ ...form, clicks })} /><NumberField label="Conversions" value={form.conversions} onChange={(conversions) => setForm({ ...form, conversions })} /><button onClick={generate} disabled={loading} className="inline-flex items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-cyan-500 to-violet-500 px-4 py-3 text-sm font-semibold text-white disabled:opacity-60 sm:col-span-2">{loading ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <ChartNoAxesCombined className="h-4 w-4" />} Generate Recommendation</button></div><div className="rounded-xl border border-white/[0.07] bg-white/[0.025] p-4">{!data ? <Empty title={error || "Recommendation belum dibuat"} /> : <Result data={data} meta={meta} />}</div></div></DashboardPanel>;
}
function Result({ data, meta }: { data: PerformanceRecommendation; meta: PerformanceRecommendationMeta | null }) { return <div><div className="flex flex-wrap gap-2"><Badge>{meta?.provider === "gemini" ? "Gemini" : "Dummy"}</Badge><Badge>{meta?.mode === "real" ? "REAL" : "FALLBACK"}</Badge><Badge>{data.decision.action}</Badge></div><p className="mt-4 text-xs leading-5 text-slate-400">{data.performance_summary}</p><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-5">{Object.entries(data.scorecard).map(([key, value]) => <div key={key} className="rounded-lg border border-white/[0.06] bg-white/[0.025] p-3 text-center"><div className="text-xl font-bold text-cyan-200">{value}</div><div className="mt-1 text-[9px] uppercase tracking-wide text-slate-600">{key.replace("_score", "")}</div></div>)}</div><div className="mt-4 rounded-lg border border-violet-300/10 bg-violet-300/[0.04] p-3"><div className="text-[10px] font-semibold uppercase tracking-wide text-violet-200">Knowledge Base suggestion</div><p className="mt-2 text-xs leading-5 text-slate-400">{data.knowledge_base_updates.learned_pattern}</p></div></div>; }
function Field({ label, value, onChange, wide }: { label: string; value: string; onChange: (value: string) => void; wide?: boolean }) { return <label className={wide ? "sm:col-span-2" : ""}><Label>{label}</Label><input value={value} onChange={(event) => onChange(event.target.value)} className="premium-input mt-1.5 px-3 py-2.5 text-sm" /></label>; }
function NumberField({ label, value, onChange }: { label: string; value: number; onChange: (value: number) => void }) { return <label><Label>{label}</Label><input type="number" min="0" value={value} onChange={(event) => onChange(Number(event.target.value))} className="premium-input mt-1.5 px-3 py-2.5 text-sm" /></label>; }
function Select({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (value: string) => void }) { return <label><Label>{label}</Label><select value={value} onChange={(event) => onChange(event.target.value)} className="premium-input mt-1.5 px-3 py-2.5 text-sm">{options.map((option) => <option key={option}>{option}</option>)}</select></label>; }
function Label({ children }: { children: React.ReactNode }) { return <span className="text-[10px] font-semibold uppercase tracking-[0.14em] text-slate-600">{children}</span>; }
function Badge({ children }: { children: React.ReactNode }) { return <span className="inline-flex items-center gap-1 rounded-full border border-cyan-300/15 bg-cyan-300/[0.06] px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wide text-cyan-100"><ShieldCheck className="h-3 w-3" />{children}</span>; }
function Empty({ title }: { title: string }) { return <div className="grid min-h-64 place-items-center text-center"><div><ChartNoAxesCombined className="mx-auto h-7 w-7 text-cyan-200" /><p className="mt-3 text-sm font-semibold text-slate-300">{title}</p><p className="mt-1 text-xs text-slate-600">Masukkan metrics manual lalu jalankan engine.</p></div></div>; }
