"use client";
import { FileCheck2, LoaderCircle, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { DashboardPanel } from "@/components/dashboard/ui";
import type { PublishingPackage, PublishingPackageMeta } from "@/lib/publishing/publishing-engine";
const initial = { platform: "tiktok", contentTitle: "Ramadan Affiliate Product #04", contentObjective: "Prepare manual export bundle", language: "Bahasa Indonesia", schedulePreference: "19:00", approvalRequired: true };
export function PublishingEnginePanel() {
  const [form, setForm] = useState(initial), [data, setData] = useState<PublishingPackage | null>(null), [meta, setMeta] = useState<PublishingPackageMeta | null>(null), [error, setError] = useState(""), [loading, setLoading] = useState(false);
  async function generate() { setLoading(true); setError(""); try { const response = await fetch("/api/publishing/package", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }), payload = await response.json(); if (!response.ok || !payload.success) throw new Error(payload.error?.message ?? "Publishing package gagal dibuat."); setData(payload.data); setMeta(payload.meta); } catch (requestError) { setData(null); setMeta(null); setError(requestError instanceof Error ? requestError.message : "Publishing package gagal dibuat."); } finally { setLoading(false); } }
  return <DashboardPanel title="Publishing Engine v1" description="Siapkan metadata, approval flow, dan export bundle untuk posting manual."><div className="grid gap-5 xl:grid-cols-[0.82fr_1.18fr]"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-1"><Field label="Content title" value={form.contentTitle} onChange={(contentTitle) => setForm({ ...form, contentTitle })} /><Field label="Objective" value={form.contentObjective} onChange={(contentObjective) => setForm({ ...form, contentObjective })} /><Select label="Platform" value={form.platform} options={["tiktok", "youtube", "instagram", "facebook", "shopee"]} onChange={(platform) => setForm({ ...form, platform })} /><label className="flex items-center gap-2 text-xs text-slate-400"><input type="checkbox" checked={form.approvalRequired} onChange={(event) => setForm({ ...form, approvalRequired: event.target.checked })} /> Approval required</label><button onClick={generate} disabled={loading} className="inline-flex items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-blue-500 to-violet-500 px-4 py-3 text-sm font-semibold text-white disabled:opacity-60">{loading ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <FileCheck2 className="h-4 w-4" />} Generate Publishing Package</button></div><div className="rounded-xl border border-white/[0.07] bg-white/[0.025] p-4">{!data ? <Empty title={error || "Publishing package belum dibuat"} /> : <Result data={data} meta={meta} />}</div></div></DashboardPanel>;
}
function Result({ data, meta }: { data: PublishingPackage; meta: PublishingPackageMeta | null }) { return <div><div className="flex flex-wrap gap-2"><Badge>{meta?.provider === "gemini" ? "Gemini" : "Dummy"}</Badge><Badge>{meta?.mode === "real" ? "REAL" : "FALLBACK"}</Badge><Badge>{data.publishing_status}</Badge></div><h3 className="mt-4 text-base font-semibold text-white">{data.final_metadata.title}</h3><p className="mt-2 text-xs leading-5 text-slate-400">{data.final_metadata.caption}</p><div className="mt-4 rounded-lg border border-cyan-300/10 bg-cyan-300/[0.04] p-3 text-xs leading-5 text-cyan-100">{data.approval_flow.telegram_preview_message}</div><div className="mt-4 grid gap-2 sm:grid-cols-2">{data.platform_checklist.map((item) => <div key={item} className="rounded-lg border border-white/[0.06] bg-white/[0.025] p-3 text-xs text-slate-400">{item}</div>)}</div></div>; }
function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label><Label>{label}</Label><input value={value} onChange={(event) => onChange(event.target.value)} className="premium-input mt-1.5 px-3 py-2.5 text-sm" /></label>; }
function Select({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (value: string) => void }) { return <label><Label>{label}</Label><select value={value} onChange={(event) => onChange(event.target.value)} className="premium-input mt-1.5 px-3 py-2.5 text-sm">{options.map((option) => <option key={option}>{option}</option>)}</select></label>; }
function Label({ children }: { children: React.ReactNode }) { return <span className="text-[10px] font-semibold uppercase tracking-[0.14em] text-slate-600">{children}</span>; }
function Badge({ children }: { children: React.ReactNode }) { return <span className="inline-flex items-center gap-1 rounded-full border border-cyan-300/15 bg-cyan-300/[0.06] px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wide text-cyan-100"><ShieldCheck className="h-3 w-3" />{children}</span>; }
function Empty({ title }: { title: string }) { return <div className="grid min-h-64 place-items-center text-center"><div><FileCheck2 className="mx-auto h-7 w-7 text-cyan-200" /><p className="mt-3 text-sm font-semibold text-slate-300">{title}</p><p className="mt-1 text-xs text-slate-600">Lengkapi title dan platform lalu jalankan engine.</p></div></div>; }
