"use client";
import { CheckCircle2, Clock3, RefreshCw, XCircle } from "lucide-react";
import { useEffect, useState } from "react";
import { DashboardPanel } from "@/components/dashboard/ui";
import type { TelegramApproval } from "@/lib/approval/telegram-approval";
export function TelegramApprovalQueue() {
  const [items, setItems] = useState<TelegramApproval[]>([]), [loading, setLoading] = useState(false);
  async function load() { setLoading(true); try { const response = await fetch("/api/approval/telegram", { cache: "no-store" }), payload = await response.json(); setItems(payload.approvals ?? []); } catch { setItems([]); } finally { setLoading(false); } }
  async function update(approvalId: string, status: "approved" | "rejected") { await fetch("/api/approval/telegram", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ approvalId, status }) }); await load(); }
  useEffect(() => { void load(); }, []);
  const count = (status: TelegramApproval["status"]) => items.filter((item) => item.status === status).length;
  return <DashboardPanel title="Telegram Approval Queue" description="Approval tetap tersedia dalam dummy mode ketika Telegram belum dikonfigurasi."><div className="grid gap-3 sm:grid-cols-3"><Summary icon={Clock3} label="Pending Review" value={count("pending")} /><Summary icon={CheckCircle2} label="Approved" value={count("approved")} /><Summary icon={XCircle} label="Rejected" value={count("rejected")} /></div><div className="mt-4 flex justify-end"><button type="button" onClick={load} className="inline-flex items-center gap-2 rounded-lg border border-white/[0.08] bg-white/[0.025] px-3 py-2 text-xs font-semibold text-slate-300"><RefreshCw className={`h-3.5 w-3.5 ${loading ? "animate-spin" : ""}`} /> Refresh</button></div>{items.length ? <div className="mt-3 space-y-2">{items.slice(0, 8).map((item) => <article key={item.approval_id} className="flex flex-col gap-3 rounded-xl border border-white/[0.06] bg-white/[0.025] p-4 md:flex-row md:items-center"><div className="flex-1"><div className="text-sm font-semibold text-slate-200">{item.content_title}</div><div className="mt-1 text-xs text-slate-500">{item.platform} · {item.mode === "telegram" ? "Telegram Connected" : "Dummy Approval"} · {item.status}</div></div>{item.status === "pending" && <div className="flex gap-2"><button onClick={() => update(item.approval_id, "approved")} className="rounded-lg border border-emerald-300/20 bg-emerald-300/[0.08] px-3 py-2 text-xs font-semibold text-emerald-200">Approve</button><button onClick={() => update(item.approval_id, "rejected")} className="rounded-lg border border-rose-300/20 bg-rose-300/[0.08] px-3 py-2 text-xs font-semibold text-rose-200">Reject</button></div>}</article>)}</div> : <div className="mt-3 rounded-xl border border-dashed border-white/[0.1] bg-white/[0.018] px-6 py-8 text-center text-xs text-slate-500">Belum ada approval request. Generate Publishing Package untuk membuat review baru.</div>}</DashboardPanel>;
}
function Summary({ icon: Icon, label, value }: { icon: typeof Clock3; label: string; value: number }) { return <div className="rounded-xl border border-white/[0.06] bg-white/[0.025] p-4"><Icon className="h-4 w-4 text-cyan-200" /><div className="mt-3 text-xl font-bold text-white">{value}</div><div className="mt-1 text-xs text-slate-500">{label}</div></div>; }
